### ISSUE TITLE
Add confidence type + score to meta data

### ISSUE THREAD

**Issue by iandaaci** [3D-Beacons/3d-beacons-client#40]
Each model needs to have the fields:
- `confidence_type`
- `confidence_avg_local_score`

This ticket is to:
- [x] add these fields to the meta-data schema
- [x] add these fields to the example json metadata files
- [x] make sure these fields are added to the outgoing data structure
